DriveEasyApplication.Web.Mvc/Controllers/DrivesController.cs
using DriveEasyApplication.Web.Mvc.Models;
using DriveEasyApplication.Web.Mvc.Services;
using Google.Apis.Auth.OAuth2;
using Google.Apis.Calendar.v3;
using Google.Apis.Calendar.v3.Data;
using Google.Apis.Services;
using Google.Apis.Sheets.v4;
using Google.Apis.Sheets.v4.Data;
using Google.Apis.Util.Store;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace DriveEasyApplication.Web.Mvc.Controllers
{
    public class DrivesController : Controller
    {
        private readonly IEasyDriveDbService _easyDriveDbService;
        public DrivesController(IEasyDriveDbService easyDriveDbService)
        {
            _easyDriveDbService = easyDriveDbService;
        }
        static string[] Scopes = {
            SheetsService.Scope.SpreadsheetsReadonly,
            CalendarService.Scope.Calendar,
            CalendarService.Scope.CalendarEvents,
            CalendarService.Scope.CalendarEventsReadonly
        };

        static string ApplicationName = "Interview Drive Google Sheets";

        #region hardcoded data
        //Drive drive = new Drive
        //{
        //    Name = "23/10/2021 HPS Merchant Drive",
        //    DriveStartTime = new DateTime(2021, 10, 23, 10, 00, 00),
        //    DriveEndTime = new DateTime(2021, 10, 23, 18, 00, 00),
        //    BreakStartTime = new DateTime(2021, 10, 23, 13, 00, 00),
        //    BreakEndTime = new DateTime(2021, 10, 23, 14, 00, 00),
        //    DriveDate = new DateTime(2021, 10, 23)
        //};

        List<PanelDetail> panelDetails = new List<PanelDetail>()
            {
                new PanelDetail
                {
                    ID = 1,
                    Name = "Sharique Nadeem",
                    EmployeeID = "TSYS111013",
                    Manager = "Dattatray Misal",
                    Department = "HPS",
                    Title = "Senior Software Engineer",
                    Experience = "7.5",
                    StartTime = new DateTime(2021, 10, 30, 9, 00, 00),
                    EndTime = new DateTime(2021, 10, 30, 16, 00, 00),
                },
                new PanelDetail
                {
                    ID = 2,
                    Name = "Mohsin Mulla",
                    EmployeeID = "TSYS111014",
                    Manager = "Dattatray Misal",
                    Department = "HPS",
                    Title = "Senior Software Engineer",
                    Experience = "7",
                    StartTime = new DateTime(2021, 10, 30, 9, 00, 00),
                    EndTime = new DateTime(2021, 10, 30, 13, 00, 00),
                },
                new PanelDetail
                {
                    ID = 3,
                    Name = "Suraj Patel",
                    EmployeeID = "TSYS111015",
                    Manager = "Dattatray Misal",
                    Department = "HPS",
                    Title = "Senior SDET Analyst",
                    Experience = "6.5",
                    StartTime = new DateTime(2021, 10, 30, 9, 00, 00),
                    EndTime = new DateTime(2021, 10, 30, 18, 00, 00),
                },
                new PanelDetail
                {
                    ID = 4,
                    Name = "Abhishek Chorage",
                    EmployeeID = "TSYS1110158",
                    Manager = "Dattatray Misal",
                    Department = "HPS",
                    Title = "Software Engineer",
                    Experience = "1.5",
                    StartTime = new DateTime(2021, 10, 30, 9, 00, 00),
                    EndTime = new DateTime(2021, 10, 30, 18, 00, 00),
                },
                new PanelDetail
                {
                    ID = 5,
                    Name = "Chandan Gupta",
                    EmployeeID = "TSYS111200",
                    Manager = "Dattatray Misal",
                    Department = "HPS",
                    Title = "Senior SDET Analyst",
                    Experience = "11",
                    StartTime = new DateTime(2021, 10, 30, 9, 00, 00),
                    EndTime = new DateTime(2021, 10, 30, 18, 00, 00),
                },
                new PanelDetail
                {
                    ID = 6,
                    Name = "Vinod Patil",
                    EmployeeID = "TSYS11125",
                    Manager = "Dattatray Misal",
                    Department = "HPS",
                    Title = "SDET Analyst",
                    Experience = "2",
                    StartTime = new DateTime(2021, 10, 30, 9, 00, 00),
                    EndTime = new DateTime(2021, 10, 30, 18, 00, 00),
                }
        };
        #endregion

        public IActionResult Index()
        {
            try
            {   
                return View(new DriveDetailsViewModel() { Drives = GetDriveDetails() });
            }
            catch(Exception ex)
            {
                return RedirectToAction("Error", "Home");
            }
        }

        public List<Drive> GetDriveDetails()
        {
            List<Drive> drivesList = new List<Drive>();
            try
            {
                using (EasyDriveDbServices easyDriveDbServices = new EasyDriveDbServices())
                {
                    //var result = easyDriveDbServices.ReadTableAsList("Drive");
                    var dbData = easyDriveDbServices.ReadTable("Drive");
                    var result  = dbData.AsEnumerable().Cast<DataRow>().ToList();
                    if (result != null && result.Count > 0)
                    {
                        foreach (DataRow dr in result)
                        {
                            Drive drive = new Drive();
                            drive.DriveID = Convert.ToInt32(dr["DriveID"]);
                            drive.Name = (string)dr["Name"];
                            drive.DriveDate = Convert.ToDateTime((string)dr["DriveDate"]);
                            drive.Department = (string)dr["Department"];
                            drive.Organizer = (string)dr["Organizer"];
                            drive.Status = (string)dr["DriveStatus"];
                            drive.DriveStatus = (int)Enum.Parse(typeof(DriveStatus), drive.Status);
                            drive.DriveStartTime = Convert.ToDateTime((string)dr["DriveStartTime"]);
                            drive.DriveEndTime = Convert.ToDateTime((string)dr["DriveEndTime"]);
                            drive.BreakStartTime = Convert.ToDateTime((string)dr["BreakStartTime"]);
                            drive.BreakEndTime = Convert.ToDateTime((string)dr["BreakEndTime"]);
                            drivesList.Add(drive);
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }            

            return drivesList.OrderByDescending(d => d.DriveID).ToList();
        }

        public List<Candidate> GetCandidateDetails(string driveId)
        {
            List<Candidate> candidatesList = new List<Candidate>();
            try
            {
                using (EasyDriveDbServices easyDriveDbServices = new EasyDriveDbServices())
                {
                    string query = $"SELECT * FROM CANDIDATE WHERE FK_DRIVEID = {Convert.ToInt32(driveId)}";
                    var result = easyDriveDbServices.ExecuteQuerryAsList(query);
                    if (result != null && result.Count > 0)
                    {
                        foreach (DataRow dr in result)
                        {
                            Candidate candidate = new Candidate();
                            candidate.CandidateID = Convert.ToInt32(dr["CandidateID"]);
                            candidate.FK_DriveID = Convert.ToInt64(driveId);
                            candidate.Name = (string)dr["Name"];
                            candidate.MobileNumber = (string)dr["MobileNumber"];
                            candidate.Skills = (string)dr["Skills"];
                            candidate.Experience = (string)dr["Experience"];
                            candidate.NoticePeriod = Convert.ToInt32(dr["NoticePeriod"]);
                            candidate.Source = (string)dr["Source"];
                            candidate.Confirmed = (string)dr["Confirmed"];
                            candidate.CurrentOrganization = (string)dr["CurrentOrganization"];
                            candidate.MeetingLink = dr["MeetingLink"] == DBNull.Value ? string.Empty : (string)dr["MeetingLink"];
                            candidate.FormattedInterviewTime = dr["InterviewTime"] == DBNull.Value || dr["InterviewTime"].ToString().Trim() == "" ? string.Empty : DateTime.ParseExact((string)dr["InterviewTime"], "MM/dd/yyyy h:mm:ss tt", CultureInfo.InvariantCulture).ToString("dd/MM/yyyy hh:mm tt");
                            candidate.TechnicalPanel = dr["TechnicalPanel"] == DBNull.Value ? string.Empty : (string)dr["TechnicalPanel"];
                            candidate.TechnicalPanelFeedback = dr["TechnicalPanelFeedback"] == DBNull.Value ? string.Empty : (string)dr["TechnicalPanelFeedback"];
                            candidate.ManagerPanel = dr["ManagerPanel"] == DBNull.Value ? string.Empty : (string)dr["ManagerPanel"];
                            candidate.ManagerPanelFeedback = dr["ManagerPanelFeedback"] == DBNull.Value ? string.Empty : (string)dr["ManagerPanelFeedback"];
                            candidate.HRPanel = dr["HRPanel"] == DBNull.Value ? string.Empty : (string)dr["HRPanel"];
                            candidate.HRPanelFeedback = dr["HRPanelFeedback"] == DBNull.Value ? string.Empty : (string)dr["HRPanelFeedback"];

DriveEasyApplication.Web.Mvc/Controllers/PanelsController.cs
using Microsoft.AspNetCore.Mvc;
using DriveEasyApplication.Web.Mvc.Models;
using DriveEasyApplication.Web.Mvc.Services;
using System.Data;
using System.Collections.Generic;
using System;
using System.Linq;

namespace DriveEasyApplication.Web.Mvc.Controllers
{
    public class PanelsController : Controller
    {
        public IActionResult Index()
        {
            try
            {
                List<PanelDetail> panelList = new List<PanelDetail>();
                using (EasyDriveDbServices easyDriveDbServices = new EasyDriveDbServices())
                {
                    var result = easyDriveDbServices.ReadTableAsList("Panel");
                    if (result != null && result.Count > 0)
                    {
                        foreach (DataRow dr in result)
                        {
                            PanelDetail pd = new PanelDetail();
                            pd.PanelID = Convert.ToInt32(dr["PanelID"]);
                            pd.Name = (string)dr["Name"];
                            pd.Email = (string)dr["Email"];
                            pd.MobileNumber = (string)dr["MobileNumber"];
                            pd.EmployeeID = (string)dr["EmployeeID"];
                            pd.Skills = (string)dr["Skills"];
                            pd.Manager = (string)dr["Manager"];
                            pd.Department = (string)dr["Department"];
                            pd.PanelRole = (string)(dr["PanelType"]);
                            pd.Experience = (string)dr["Experience"];
                            pd.Title = (string)dr["Title"];
                            panelList.Add(pd);
                        }
                    }
                    return View(panelList.OrderByDescending(p => p.PanelID).ToList());
                }
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home");
            }
        }

        [HttpPost]
        public IActionResult AddPanel(PanelDetail panelDetail)
        {
            try
            {
                using (EasyDriveDbServices easyDriveDbServices = new EasyDriveDbServices())
                {
                    string query = $"insert into panel('Name', 'Email', 'MobileNumber', 'EmployeeID', " +
                        $"'Skills', 'Manager', 'Department', 'PanelType', 'Experience', 'Title')" +
                        $"values('{panelDetail.Name}', '{panelDetail.Email}', '{panelDetail.MobileNumber}', '{panelDetail.EmployeeID}', " +
                        $"'{panelDetail.Skills}', '{panelDetail.Manager}', '{panelDetail.Department}', '{panelDetail.PanelRole}', '{panelDetail.Experience}', '{panelDetail.Title}')";
                    var result = easyDriveDbServices.ExecuteQuerryAsList(query);
                    // easyDriveDbServices.Add<PanelDetail>(panelDetail);
                    return Ok("success");
                }
            }
            catch(Exception ex)
            {
                return RedirectToAction("Error", "Home");
            }
        }

        public IActionResult Edit(string panelId)
        {
            return RedirectToAction("Index");
        }

        public IActionResult Delete(string panelId)
        {
            return RedirectToAction("Index");
        }

    }
}

DriveEasyApplication.Web.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DriveEasyApplication</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bbootstrap 4 -->
    <link rel="stylesheet" href="~/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="~/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- JQVMap -->
    <link rel="stylesheet" href="~/plugins/jqvmap/jqvmap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/dist/css/adminlte.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="~/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="~/plugins/daterangepicker/daterangepicker.css">
    <!-- summernote -->
    <link rel="stylesheet" href="~/plugins/summernote/summernote-bs4.css">
    <!-- jQuery -->
    <script src="~/plugins/jquery/jquery.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="~/plugins/jquery-ui/jquery-ui.min.js"></script>
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    @*<a href=@Url.Action("Index","Home") class="nav-link">Home</a>*@
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    @*<a href=@Url.Action("Index","User") class="nav-link">User Info</a>*@
                </li>
                @*<li class="nav-item d-none d-sm-inline-block">
                        <a href="@Url.Action("ProjectDetails","Home")" class="nav-link">Project-wise Status</a>
                    </li>*@
            </ul>

            <!-- SEARCH FORM -->
            <form class="form-inline ml-12">
                <div class="input-group input-group-sm">
                    <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                    <div class="input-group-append">
                        <button class="btn btn-navbar" type="submit">
                            <i class="fas fa-search"></i>
                        </button>
                    </div>
                </div>
            </form>

            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">               
                <li class="nav-item">
                    <a class="btn btn-outline-success btn-large" href=@Url.Action("Index","Login")>
                        <span class="hidden-xs">Log Out</span>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="@Url.Action("Index","Home")" class="brand-link">
                <img src="~/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
                     style="opacity: .8">
                <span class="brand-text font-weight-light">Drive Easy Application</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">
                        <img src="~/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
                    </div>
                    <div class="info">
                        <a href="#" class="d-block">Sharique</a>
                        <!-- Status -->
                        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                    </div>
                </div>

                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
                        with font-awesome or any other icon font library -->
                        <li class="nav-item has-treeview menu-open">
                            <a href=@Url.Action("Index","Home") class="nav-link active">
                                <i class="nav-icon fab fa-buromobelexperte"></i>
                                <p>
                                    Dashboard
                                </p>
                            </a>
                        <li class="nav-item has-treeview menu-open">
                            <a href="@Url.Action("Index","Drives")" class="nav-link">
                                <i class="nav-icon fas fa-tachometer-alt"></i>
                                <p>
                                    Drives
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("Index","Panels")" class="nav-link">
                                <i class="nav-icon fas fa-users"></i>
                                <p>
                                    Panels
                                </p>
                            </a>
                        </li>
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <div class="content-wrapper">
            <main role="main" class="content">
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </main>
        </div>

        <footer class="main-footer">
            <strong>Copyright &copy; 2021 <a href=#>DriveEasyApplication</a>.</strong>
            All rights reserved.
            <div class="float-right d-none d-sm-inline-block">
                <b>Version</b> 1.0.0
            </div>
        </footer>

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>

    @*@RenderSection("Scripts", required: false)*@

    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
            $.widget.bridge('uibutton', $.ui.button)
        </script>
    <!-- Bootstrap 4 -->
    <script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/dist/js/adminlte.js"></script>

    <!-- ChartJS -->
    <script src="~/plugins/chart.js/Chart.min.js"></script>
    <!-- Sparkline -->
    <script src="~/plugins/sparklines/sparkline.js"></script>
    <!-- JQVMap -->
    <script src="~/plugins/jqvmap/jquery.vmap.min.js"></script>
    <script src="~/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
    <!-- jQuery Knob Chart -->
    <script src="~/plugins/jquery-knob/jquery.knob.min.js"></script>
    <!-- daterangepicker -->
    <script src="~/plugins/moment/moment.min.js"></script>
    <script src="~/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="~/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    <!-- Summernote -->
    <script src="~/plugins/summernote/summernote-bs4.min.js"></script>
    <!-- overlayScrollbars -->
    <script src="~/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <!-- DataTables  & Plugins -->
    <script src="~/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
    <script src="~/plugins/jszip/jszip.min.js"></script>
    <script src="~/plugins/pdfmake/pdfmake.min.js"></script>
    <script src="~/plugins/pdfmake/vfs_fonts.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.print.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/dist/js/adminlte.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="~/dist/js/pages/dashboard.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/dist/js/demo.js"></script>

    <script>
        $(document).ready(function () {

        })
    </script>

    @RenderSection("Scripts", required: false)
</body>
</html>